Lidar_front_end:
   lidar_type: 2   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 16
   using_raw_point: 1
   point_step: 1
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01          # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1         # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 0         # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]
   control_image_freq: 6.0 # The frequency [default = 10]

r3live_vio:
   # image_width: 1280
   # image_height: 1024
   image_width: 640
   image_height: 512
   camera_intrinsic:
      [431.88, 0.0, 324.299,
      0.0,  431.06, 252.805,
      0.0, 0.0, 1.0 ]
   camera_dist_coeffs: [-0.058 , 0.1031  , -0.00066825 , -0.04018816 , -0.000887]  #k1, k2, p1, p2, k3


   # Fine extrinsic value. form camera-LiDAR calibration.
   # 多次联合标定的均值 用这个
   camera_ext_R:
         [0.0431643,  0.0684185 , 0.9967225,
         -0.9987869, -0.0207063, 0.0446751,
         0.0236951,  -0.9974418, 0.0674417]
   camera_ext_t: [0.012,  0.066, 0.044]

   # static const Eigen::Vector3d Lidar_offset_to_IMU(0.088, 0.156, 0.154); // v2 define

   # camera_ext_t: [-0.411726,   0.215976,  -0.380464]
   # Rough extrinsic value, form CAD model, is not correct enough, but can be online calibrated in our datasets.
   # camera_ext_R:
   #    [0, 0, 1,
   #     -1, 0, 0,
   #     0, -1, 0]
   # camera_ext_t: [0,0,0]

   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0.0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30
   filter_size_surf: 0.40
   filter_size_surf_z: 0.40
   filter_size_map: 0.50